### ISSUE TITLE
Question - binding history-search-backward?

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#8]
Hi, I'm using linefeed to implement the `history-search-backward` in bash. Say I have this in history:
```
$ echo foo
$ ls src/
$ echo bar
```
Then, in shell, I type:
```
$ ec<UP>
```
and I should get `echo bar` in command line. I have this implemented [here](https://github.com/mitnk/cicada/blob/8d85e5983d255ea3bcedd3c8ff3c856a763794a0/src/binds.rs#L7-L8).

However, after `echo bar` shows up, a second `<UP>` key should fetch `echo foo`, (didn't get this implemented). Any suggestions to implement the second `<UP>` key bindings?

**Comment by murarth** [comment]
For this, you would need to access the line of history currently being edited. The `Reader` instance keeps track of this, but it had not been exposed publicly. I've pushed a new commit (and published to crates.io under version 0.2.4) that adds the method `Reader::history_index` for this purpose.

**Comment by mitnk** [comment]
Hi @murarth, Thanks for your new code. Maybe what [I'm using](https://github.com/mitnk/cicada/blob/8d85e5983d255ea3bcedd3c8ff3c856a763794a0/src/binds.rs#L7-L8) is not a correct way of fetching history, but I still not sure how to implement what I want with `history_index`. Could you please provide more info?

> you would need to access the line of history currently being edited.

I suppose I'm not editing history, only fetching? What I've using in `linefeed:: Function::execute()` does not have a way to hold the context of last time fetching.

**Comment by mitnk** [comment]
Also, with `reverse-i-search`, i.e. `Ctrl-R` to do reverse search using linefeed, it only can find the the first wanted result. A second `Ctrl-R` doesn't have any effects (does not fetch the second match history item). This issue is quite similar to my issue.

**Comment by murarth** [comment]
@mitnk: `reader.history()` returns an iterator, so you can use iterator methods to select which parts of the iterator you want to process, based on the result of `reader.history_index()`. Something like this would do the job, I think:

```rust
let history = reader.history();
let n = reader.history_index().unwrap_or(history.len());
let history = history.take(n).rev(); // Only entries before the current
```

For your second question, Ctrl-R isn't capable of that that only because I didn't know that GNU Readline's Ctrl-R was capable of that. That's quite a neat feature and I'll be sure to implement it in `linefeed` very soon.

**Comment by mitnk** [comment]
```rust
let history = history.take(n).rev(); // Only entries before the current
```
I guess I need to store `n` somewhere between two `<UP>` hitting?

This is where I'm trying to store this "n":
```rust
pub struct UpKeyFunction {
    pub q: String,
    pub idx: i32,
}
impl<Term: Terminal> Function<Term> for UpKeyFunction {
    fn execute(&self, reader: &mut Reader<Term>, _count: i32, _ch: char) -> io::Result<()> {
        let line = reader.buffer().to_string();
        if self.q != line {
            self.q = line;
            self.idx = -1;
        }

        let mut record = String::new();
        for (i, x) in reader.history().rev().enumerate() {
            if self.idx != -1 and i <= self.idx {
                // means this is not the first <UP> typing
                continue;
            }
            let s = x.to_string();
            if s.starts_with(line.as_str()) {
                self.idx = i;
                record = s.clone();
                break;
            }
        }

        let pos = reader.cursor();
        reader.delete_range(..pos).expect("delete_range error.");
        reader.insert_str(record.as_str())
    }
}
```
I cannot do/test it right now, because it's `&self` defined in linefeed, not `&mut self`.

Ideas on this?

**Comment by murarth** [comment]
Instead of modifying the buffer, I think this command would work better if you instead selected a history entry as the entry currently under modification. This is how builtin commands that operate on history work. The method `Reader::select_history_entry` serves this purpose, but it is currently private. I'll make it public and push that change when the update to Ctrl-R is complete.

**Comment by mitnk** [comment]
Ah, now I guess I understand what you mean by using `.history_index`. Look forward to using it :)

**Comment by murarth** [comment]
Okay, I've pushed the above two changes: making `Reader::select_history_entry` public and implementing next match behavior for the commands `reverse-search-history` (Ctrl-R) and `forward-search-history`. It's also been published to crates.io. Let me know if it's all working as expected or if there's anything else missing.

**Comment by mitnk** [comment]
have a quick check on Ctrl-R, seems has bugs, panic rust:
```
(reverse-i-search)`a': rm Cthread 'main' panicked at 'byte index 6 is out of bounds of `ls`', src/libcore/str/mod.rs:2165
stack backtrace:
   0:        0x1090b36e3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h34a7b169ac42b490
   1:        0x1090b7708 - std::panicking::default_hook::{{closure}}::hcc7f46907143dca1
   2:        0x1090b734c - std::panicking::default_hook::h9cd165f254d86e53
   3:        0x1090b9af7 - std::panicking::rust_panic_with_hook::h2bd2f0b446f0face
   4:        0x1090b9994 - std::panicking::begin_panic::h1732f61ecaaa434e
   5:        0x1090b9902 - std::panicking::begin_panic_fmt::h2948dd4668f99175
   6:        0x1090b9867 - rust_begin_unwind
   7:        0x1090e40e0 - core::panicking::panic_fmt::hb2e726f3b579b19d
   8:        0x1090e5183 - core::str::slice_error_fail::h0c66541771043cec
   9:        0x108e49f84 - core::str::traits::<impl core::ops::Index<core::ops::RangeTo<usize>> for str>::index::h9ac9ede7a6317181
  10:        0x108e2b71a - <linefeed::reader::Reader<Term>>::search_history_backward::h0896102e9d257f81
  11:        0x108e29280 - <linefeed::reader::Reader<Term>>::search_history_update::hff35c7ea2f69aaf8
  12:        0x108e19b3f - <linefeed::reader::Reader<Term>>::read_line_impl::h46f59e651e0c7cd8
  13:        0x108e2e168 - <linefeed::reader::Reader<Term>>::read_line::h2f134ab587e44416
  14:        0x108ea0f1d - cicada::main::h881c5573b01d3624
  15:        0x1090babea - __rust_maybe_catch_panic
  16:        0x1090b9f74 - std::rt::lang_start::h1cb64d2994eb2d7c
  17:        0x108eb27b9 - main
make: *** [run] Error 101
```
This error shows up when I type three chars like `awk`, and there has two-char history like `cd` or `ls`.

v0.2.3 no such issue.

**Comment by mitnk** [comment]
For my original issue - now the `history_index` is saved and I can fetch it when I do `<UP>` key searching. The problem now is that my original search string is not saved:
```
# say I have four history
$ echo foo
$ ls
$ echo bar
$ cd
$
```
now I type `$ ec<UP>` to search - linefeed uses `reader.buffer()` to know I'm searching `ec` reversely, and `echo bar` matches and its index is `2`, so it calls `reader.select_history_entry(2)` to fill the command line buffer with `echo bar` and the `history_index` become `2` (from None).

Now I type `<UP>` again - what I really want is to fetch next match item to `ec`, i.e. `echo foo`, but linefeed now already forget the query string `ec`, and only knows from buffer as `echo bar`, and thus does not think `echo foo` matches.

So I think to implement what I needed, I still need to store the **original** "query string" somewhere as I've showed it in [this thread](https://github.com/murarth/linefeed/issues/8#issuecomment-301289590).

I hope I make myself clear here. And ideas on this again? :)

**Comment by murarth** [comment]
I've fixed the panic in Ctrl-R.

For your second issue, I've added a new method, `Reader::backup_buffer`, that returns the original buffer while the user is editing history.

**Comment by mitnk** [comment]
All works perfect now! Thanks a lot for all these awesome work!
